name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull Dolfin-adjoint image
        run: docker pull ghcr.io/dolfin-adjoint/dolfin-adjoint:latest

      - name: Install Python dependencies inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ghcr.io/dolfin-adjoint/dolfin-adjoint:latest \
            bash -c "pip install pandas meshio matplotlib python-gmsh"

      - name: Run Python script inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ghcr.io/dolfin-adjoint/dolfin-adjoint:latest \
            bash -c "mkdir -p /tmp/run && cp -r /workspace/* /tmp/run/ && cd /tmp/run && python3 opt_DG0/opt_script.py"
