name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-docker:
    name: Test with Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull Dolfin-adjoint image
        run: docker pull ghcr.io/dolfin-adjoint/dolfin-adjoint:latest

      - name: Build custom image with dependencies
        run: |
          # Run a container with the repo mounted and install the local package inside /workspace
          docker run --name installer \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/dolfin-adjoint/dolfin-adjoint:latest \
            bash -c "pip install ."

          # Commit the container with the installed package into a new image named 'custom-image'
          docker commit installer custom-image:latest
          # Remove the installer container (if still present)
          docker rm -f installer || true

      - name: Run basic test (MPI)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            custom-image:latest \
            bash -c "mkdir -p /tmp/run && cp -r /workspace/* /tmp/run/ && cd /tmp/run && mpirun -np 4 pytest -v test"

      - name: Run basic test (serial)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            custom-image:latest \
            bash -c "mkdir -p /tmp/run && cp -r /workspace/* /tmp/run/ && cd /tmp/run && pytest -v test"