name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull Dolfin-adjoint image
        run: docker pull ghcr.io/dolfin-adjoint/dolfin-adjoint:latest

      - name: Build custom image with dependencies
        run: |
          # Give the running container a name so we can reference it later
          docker run --name installer ghcr.io/dolfin-adjoint/dolfin-adjoint:latest \
            bash -c "pip install ."
          
          # Commit the container with the new packages into a new image named 'custom-image'
          docker commit installer custom-image:latest

      - name: Run Python script inside custom container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            custom-image:latest \
            bash -c "mkdir -p /tmp/run && cp -r /workspace/* /tmp/run/ && cd /tmp/run && python3 opt_DG0/opt_script.py"